/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/act` | `/act`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pref` | `/pref`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rest` | `/rest`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/act` | `/act`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/contact` | `/contact`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pref` | `/pref`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/rest` | `/rest`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/act${`?${string}` | `#${string}` | ''}` | `/act${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/contact${`?${string}` | `#${string}` | ''}` | `/contact${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pref${`?${string}` | `#${string}` | ''}` | `/pref${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/rest${`?${string}` | `#${string}` | ''}` | `/rest${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/act` | `/act`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/contact` | `/contact`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pref` | `/pref`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/rest` | `/rest`; params?: Router.UnknownInputParams; };
    }
  }
}
